# Generated by Django 3.0.2 on 2020-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedayclass', '0002_auto_20200210_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayclass',
            name='gender',
            field=models.CharField(choices=[('F', '여'), ('M', '남')], default='F', max_length=1, verbose_name='강사 성별'),
        ),
        migrations.AlterField(
            model_name='onedayclass',
            name='price',
            field=models.PositiveIntegerField(help_text='단위: 원', verbose_name='비용'),
        ),
    ]
