# Generated by Django 3.0.2 on 2020-02-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedayclass', '0003_auto_20200212_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayclass',
            name='theme',
            field=models.CharField(choices=[('1', '일반'), ('2', '임산부'), ('3', '키즈')], default='1', max_length=1, verbose_name='수업 테마'),
        ),
        migrations.AlterField(
            model_name='onedayclass',
            name='type',
            field=models.CharField(choices=[('요가', '요가'), ('필라테스', '필라테스')], default='Y', max_length=4, verbose_name='클래스 종류'),
        ),
    ]
