# Generated by Django 3.0.2 on 2020-03-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedayclass', '0004_auto_20200221_1448'),
        ('onedayclass', '0004_auto_20200226_1600'),
    ]

    operations = [
    ]
