# Generated by Django 3.0.2 on 2020-03-19 20:31

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='센터명')),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('요가', '요가'), ('필라테스', '필라테스')], max_length=7, verbose_name='센터 종류')),
                ('detail', models.CharField(choices=[('1', '여성전용'), ('2', '여남공용'), ('3', '남성전용')], default='1', max_length=1, verbose_name='전용시설')),
                ('price', models.TextField(verbose_name='이용가격')),
                ('info', models.TextField(verbose_name='이용정보')),
                ('event', models.ImageField(null=True, upload_to='center/event/', verbose_name='이벤트')),
                ('schedule', models.ImageField(help_text='스케줄표를 이미지로 업로드해주세요', null=True, upload_to='center/schedule/', verbose_name='스케줄표')),
                ('phone', models.CharField(max_length=20, verbose_name='센터 전화번호')),
                ('address', models.CharField(max_length=200, verbose_name='센터 주소')),
                ('site', models.URLField(max_length=250, verbose_name='센터 사이트 주소')),
            ],
        ),
        migrations.CreateModel(
            name='CenterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='center/img/', verbose_name='센터 사진1')),
                ('image2', models.ImageField(null=True, upload_to='center/img/', verbose_name='센터 사진2')),
                ('image3', models.ImageField(null=True, upload_to='center/img/', verbose_name='센터 사진3')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_image', to='center.Center', verbose_name='센터명')),
            ],
        ),
    ]
