# Generated by Django 3.0.2 on 2020-02-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='type',
        ),
        migrations.AlterField(
            model_name='centerimage',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_image', to='center.Center', verbose_name='센터명'),
        ),
    ]
