# Generated by Django 3.0.2 on 2020-02-09 16:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_center_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '요가'), ('2', '필라테스')], default='1', max_length=1, verbose_name='센터 종류'),
        ),
    ]
