# Generated by Django 3.0.2 on 2020-02-09 16:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20200210_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '요가'), ('2', '필라테스')], max_length=3, verbose_name='센터 종류'),
        ),
    ]
